In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
import loaders

In [3]:
book_authors = {
    "Genesis": "Moses",
    "Exodus": "Moses",
    "Leviticus": "Moses",
    "Numbers": "Moses",
    "Deuteronomy": "Moses",
    "Joshua": "Joshua",
    "Judges": "Samuel; Nathan; Gad",
    "Ruth": "Samuel",
    "1 Samuel": "Samuel; Nathan; Gad",
    "2 Samuel": "Gad; Nathan",
    "1 Kings": "Jeremiah",
    "2 Kings": "Jeremiah",
    "1 Chronicles": "Ezra",
    "2 Chronicles": "Ezra",
    "Ezra": "Ezra",
    "Nehemiah": "Nehemiah",
    "Esther": "Mordecai",
    "Job": "Unknown",
    "Psalms": "David and others",
    "Proverbs": "Solomon; Agur; Lemuel",
    "Ecclesiastes": "Solomon",
    "Song of Songs": "Solomon",
    "Isaiah": "Isaiah",
    "Jeremiah": "Jeremiah",
    "Lamentations": "Jeremiah",
    "Ezekiel": "Ezekiel",
    "Daniel": "Daniel",
    "Hosea": "Hosea",
    "Joel": "Joel",
    "Amos": "Amos",
    "Obadiah": "Obadiah",
    "Jonah": "Jonah",
    "Micah": "Micah",
    "Nahum": "Nahum",
    "Habakkuk": "Habakkuk",
    "Zephaniah": "Zephaniah",
    "Haggai": "Haggai",
    "Zechariah": "Zechariah",
    "Malachi": "Malachi",
    "Matthew": "Matthew",
    "Mark": "Mark",
    "Luke": "Luke",
    "John": "John",
    "Acts": "Luke",
    "Romans": "Paul",
    "1 Corinthians": "Paul",
    "2 Corinthians": "Paul",
    "Galatians": "Paul",
    "Ephesians": "Paul",
    "Philippians": "Paul",
    "Colossians": "Paul",
    "1 Thessalonians": "Paul",
    "2 Thessalonians": "Paul",
    "1 Timothy": "Paul",
    "2 Timothy": "Paul",
    "Titus": "Paul",
    "Philemon": "Paul",
    "Hebrews": "Unknown",
    "James": "James",
    "1 Peter": "Peter",
    "2 Peter": "Peter",
    "1 John": "John",
    "2 John": "John",
    "3 John": "John",
    "Jude": "Jude",
    "Revelation": "John"
}

In [4]:
sept = loaders.load_sept()
tisch = loaders.load_tisch()
references = loaders.load_munged_references()

### Does Matthew Contain more OT references than John?

In [5]:
references[references['n_start'].str[0] == "Matthew"]

,n_start,n_end,o_start,o_end,new_text,old_text
0,"(Matthew, 1, 1)","(Matthew, 1, 2)","(Genesis, 25, 19)","(Genesis, 25, 20)",βίβλος γενέσεως ἰησοῦ χριστοῦ υἱοῦ δαυεὶδ υἱοῦ...,και αυται αι γενεσεις ισαακ του υιου αβρααμ αβ...
1,"(Matthew, 1, 21)","(Matthew, 1, 21)","(Genesis, 16, 11)","(Genesis, 16, 11)",τέξεται δὲ υἱὸν καὶ καλέσεις τὸ ὄνομα αὐτοῦ ἰη...,και ειπεν αυτη ο αγγελος κυριου ιδου συ εν γασ...
2,"(Matthew, 1, 21)","(Matthew, 1, 21)","(Genesis, 17, 19)","(Genesis, 17, 19)",τέξεται δὲ υἱὸν καὶ καλέσεις τὸ ὄνομα αὐτοῦ ἰη...,ειπεν δε ο θεος τω αβρααμ ναι ιδου σαρρα η γυν...
3,"(Matthew, 1, 21)","(Matthew, 1, 21)","(Genesis, 19, 37)","(Genesis, 19, 37)",τέξεται δὲ υἱὸν καὶ καλέσεις τὸ ὄνομα αὐτοῦ ἰη...,και ετεκεν η πρεσβυτερα υιον και εκαλεσεν το ο...
4,"(Matthew, 1, 21)","(Matthew, 1, 21)","(Genesis, 19, 38)","(Genesis, 19, 38)",τέξεται δὲ υἱὸν καὶ καλέσεις τὸ ὄνομα αὐτοῦ ἰη...,ετεκεν δε και η νεωτερα υιον και εκαλεσεν το ο...
...,...,...,...,...,...,...
187,"(Matthew, 23, 39)","(Matthew, 24, 1)","(Psalms, 118, 26)","(Psalms, 118, 26)",λέγω γὰρ ὑμῖν οὐ μή με ἴδητε ἀπ' ἄρτι ἕως ἂν ε...,ευλογημενος ο ερχομενος εν ονοματι κυριου ευλο...
188,"(Matthew, 26, 29)","(Matthew, 26, 30)","(2 Samuel, 16, 3)","(2 Samuel, 16, 4)",λέγω δὲ ὑμῖν οὐ μὴ πίω ἀπ' ἄρτι ἐκ τούτου τοῦ ...,και ειπεν ο βασιλευς και που ο υιος του κυριου...
189,"(Matthew, 26, 67)","(Matthew, 26, 67)","(Deuteronomy, 25, 9)","(Deuteronomy, 25, 9)",τότε ἐνέπτυσαν εἰς τὸ πρόσωπον αὐτοῦ καὶ ἐκολά...,και προσελθουσα η γυνη του αδελφου αυτου εναντ...
190,"(Matthew, 27, 9)","(Matthew, 27, 10)","(Exodus, 30, 16)","(Exodus, 30, 16)",τότε ἐπληρώθη τὸ ῥηθὲν διὰ ἰερεμίου τοῦ προφήτ...,και λημψη το αργυριον της εισφορας παρα των υι...
191,"(Matthew, 27, 29)","(Matthew, 27, 29)","(2 Samuel, 13, 19)","(2 Samuel, 13, 19)",καὶ πλέξαντες στέφανον ἐξ ἀκανθῶν ἐπέθηκαν ἐπὶ...,και ελαβεν θημαρ σποδον και επεθηκεν επι την κ...

In [6]:
matthew_v_john = references[(references['n_start'].str[0] == "Matthew") | (references['n_start'].str[0] == "John")]
display(matthew_v_john.head(2))
display(matthew_v_john.tail(2))

,n_start,n_end,o_start,o_end,new_text,old_text
0,"(Matthew, 1, 1)","(Matthew, 1, 2)","(Genesis, 25, 19)","(Genesis, 25, 20)",βίβλος γενέσεως ἰησοῦ χριστοῦ υἱοῦ δαυεὶδ υἱοῦ...,και αυται αι γενεσεις ισαακ του υιου αβρααμ αβ...
1,"(Matthew, 1, 21)","(Matthew, 1, 21)","(Genesis, 16, 11)","(Genesis, 16, 11)",τέξεται δὲ υἱὸν καὶ καλέσεις τὸ ὄνομα αὐτοῦ ἰη...,και ειπεν αυτη ο αγγελος κυριου ιδου συ εν γασ...

,n_start,n_end,o_start,o_end,new_text,old_text
726,"(John, 19, 24)","(John, 19, 24)","(Psalms, 22, 18)","(Psalms, 22, 19)",εἶπαν οὖν πρὸς ἀλλήλους μὴ σχίσωμεν αὐτόν ἀλλὰ...,διεμερισαντο τα ιματια μου εαυτοις και επι τον...
727,"(John, 20, 17)","(John, 20, 17)","(Genesis, 45, 9)","(Genesis, 45, 9)",λέγει αὐτῇ ἰησοῦς μή μου ἅπτου οὔπω γὰρ ἀναβέβ...,σπευσαντες ουν αναβητε προς τον πατερα μου και...

In [7]:
px.histogram(
    x = matthew_v_john['n_start'].str[0],
    labels = {'x':'', 'y':''},
    title = "Which has more Allusions, Matthew or John?"
)

In [8]:
matthew_v_john['n_start'].str[0].value_counts().to_frame()

         count
n_start
Matthew    192
John        58

#### Percentage of Author Allusions

In [9]:
references['n_start'].str[0]

0          Matthew
1          Matthew
2          Matthew
3          Matthew
4          Matthew
           ...
1479    Revelation
1480    Revelation
1481    Revelation
1482    Revelation
1483    Revelation
Name: n_start, Length: 1484, dtype: object

In [10]:
references['n_start'].str[0].map(book_authors).value_counts().to_frame().reset_index()

   n_start  count
0     Luke    481
1     Mark    224
2  Unknown    199
3  Matthew    192
4     Paul    180
5     John    168
6    Peter     35
7    James      5

In [11]:
fig = px.pie(
    references['n_start'].str[0].map(book_authors).value_counts().to_frame().reset_index(),
    names = "n_start",
    values= "count",
    title= "Percentage of references made by each Author in the NT."
)
fig.update_traces(textposition='inside', textinfo='percent+label', showlegend=False)
fig.show()

#### Most quoted old testatement texts

In [12]:
references

,n_start,n_end,o_start,o_end,new_text,old_text
0,"(Matthew, 1, 1)","(Matthew, 1, 2)","(Genesis, 25, 19)","(Genesis, 25, 20)",βίβλος γενέσεως ἰησοῦ χριστοῦ υἱοῦ δαυεὶδ υἱοῦ...,και αυται αι γενεσεις ισαακ του υιου αβρααμ αβ...
1,"(Matthew, 1, 21)","(Matthew, 1, 21)","(Genesis, 16, 11)","(Genesis, 16, 11)",τέξεται δὲ υἱὸν καὶ καλέσεις τὸ ὄνομα αὐτοῦ ἰη...,και ειπεν αυτη ο αγγελος κυριου ιδου συ εν γασ...
2,"(Matthew, 1, 21)","(Matthew, 1, 21)","(Genesis, 17, 19)","(Genesis, 17, 19)",τέξεται δὲ υἱὸν καὶ καλέσεις τὸ ὄνομα αὐτοῦ ἰη...,ειπεν δε ο θεος τω αβρααμ ναι ιδου σαρρα η γυν...
3,"(Matthew, 1, 21)","(Matthew, 1, 21)","(Genesis, 19, 37)","(Genesis, 19, 37)",τέξεται δὲ υἱὸν καὶ καλέσεις τὸ ὄνομα αὐτοῦ ἰη...,και ετεκεν η πρεσβυτερα υιον και εκαλεσεν το ο...
4,"(Matthew, 1, 21)","(Matthew, 1, 21)","(Genesis, 19, 38)","(Genesis, 19, 38)",τέξεται δὲ υἱὸν καὶ καλέσεις τὸ ὄνομα αὐτοῦ ἰη...,ετεκεν δε και η νεωτερα υιον και εκαλεσεν το ο...
...,...,...,...,...,...,...
1479,"(Revelation, 22, 18)","(Revelation, 22, 19)","(2 Chronicles, 34, 21)","(2 Chronicles, 34, 22)",μαρτυρῶ ἐγὼ παντὶ τῷ ἀκούοντι τοὺς λόγους τῆς ...,πορευθητε ζητησατε τον κυριον περι εμου και πε...
1480,"(Revelation, 22, 18)","(Revelation, 22, 19)","(Jeremiah, 25, 13)","(Jeremiah, 25, 15)",μαρτυρῶ ἐγὼ παντὶ τῷ ἀκούοντι τοὺς λόγους τῆς ...,και επαξω επι την γην εκεινην παντας τους λογο...
1481,"(Revelation, 22, 19)","(Revelation, 22, 20)","(Deuteronomy, 28, 58)","(Deuteronomy, 28, 58)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,εαν μη εισακουσητε ποιειν παντα τα ρηματα του ...
1482,"(Revelation, 22, 19)","(Revelation, 22, 20)","(2 Chronicles, 34, 21)","(2 Chronicles, 34, 22)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,πορευθητε ζητησατε τον κυριον περι εμου και πε...
1483,"(Revelation, 22, 19)","(Revelation, 22, 20)","(Jeremiah, 25, 13)","(Jeremiah, 25, 15)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,και επαξω επι την γην εκεινην παντας τους λογο...

In [20]:
references['o_start'].str[0].map(book_authors)

0          Moses
1          Moses
2          Moses
3          Moses
4          Moses
          ...
1479        Ezra
1480    Jeremiah
1481       Moses
1482        Ezra
1483    Jeremiah
Name: o_start, Length: 1484, dtype: object

In [29]:
references['o_start'].str[0].value_counts().to_frame().reset_index()

         o_start  count
0         Psalms    398
1         Isaiah    184
2    Deuteronomy    174
3        Genesis    148
4         Exodus     81
5       Jeremiah     63
6         Joshua     59
7         Judges     46
8           Joel     34
9       2 Samuel     31
10  1 Chronicles     31
11       2 Kings     30
12      Proverbs     26
13  2 Chronicles     23
14      1 Samuel     19
15        Daniel     17
16       1 Kings     17
17          Amos     16
18     Zechariah     16
19     Leviticus     14
20          Ruth     11
21       Ezekiel      8
22      Nehemiah      8
23       Numbers      7
24         Jonah      7
25        Esther      4
26          Ezra      3
27      Habakkuk      2
28         Hosea      2
29       Malachi      2
30         Micah      1
31  Ecclesiastes      1
32           Job      1

In [43]:
ot_references

         o_start  count
0         Psalms    398
1         Isaiah    184
2    Deuteronomy    174
3        Genesis    148
4         Exodus     81
5       Jeremiah     63
6         Joshua     59
7         Judges     46
8           Joel     34
9       2 Samuel     31
10  1 Chronicles     31
11       2 Kings     30
12      Proverbs     26
13  2 Chronicles     23
14      1 Samuel     19
15        Daniel     17
16       1 Kings     17
17          Amos     16
18     Zechariah     16
19     Leviticus     14
20          Ruth     11
21       Ezekiel      8
22      Nehemiah      8
23       Numbers      7
24         Jonah      7
25        Esther      4
26          Ezra      3
27      Habakkuk      2
28         Hosea      2
29       Malachi      2
30         Micah      1
31  Ecclesiastes      1
32           Job      1

In [58]:
ot_references = references['o_start'].str[0].value_counts().to_frame().reset_index()
rare_index = ot_references[ot_references['count'] < 12].index
ot_references.loc[rare_index, "o_start"] = "Other"
ot_references['color'] = ot_references['o_start'].apply(lambda book: "red" if book == "Other" else 'blue')
ot_references.head()

       o_start  count color
0       Psalms    398  blue
1       Isaiah    184  blue
2  Deuteronomy    174  blue
3      Genesis    148  blue
4       Exodus     81  blue

In [63]:
fig = px.histogram(
    ot_references,
    x = "o_start",
    y = "count",
    color = "color"
)
fig.update_traces(showlegend=False)
fig.show()