In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import loaders

In [2]:
book_authors = {
    "Genesis": "Moses",
    "Exodus": "Moses",
    "Leviticus": "Moses",
    "Numbers": "Moses",
    "Deuteronomy": "Moses",
    "Joshua": "Joshua",
    "Judges": "Samuel; Nathan; Gad",
    "Ruth": "Samuel",
    "1 Samuel": "Samuel; Nathan; Gad",
    "2 Samuel": "Gad; Nathan",
    "1 Kings": "Jeremiah",
    "2 Kings": "Jeremiah",
    "1 Chronicles": "Ezra",
    "2 Chronicles": "Ezra",
    "Ezra": "Ezra",
    "Nehemiah": "Nehemiah",
    "Esther": "Mordecai",
    "Job": "Unknown",
    "Psalms": "David and others",
    "Proverbs": "Solomon; Agur; Lemuel",
    "Ecclesiastes": "Solomon",
    "Song of Songs": "Solomon",
    "Isaiah": "Isaiah",
    "Jeremiah": "Jeremiah",
    "Lamentations": "Jeremiah",
    "Ezekiel": "Ezekiel",
    "Daniel": "Daniel",
    "Hosea": "Hosea",
    "Joel": "Joel",
    "Amos": "Amos",
    "Obadiah": "Obadiah",
    "Jonah": "Jonah",
    "Micah": "Micah",
    "Nahum": "Nahum",
    "Habakkuk": "Habakkuk",
    "Zephaniah": "Zephaniah",
    "Haggai": "Haggai",
    "Zechariah": "Zechariah",
    "Malachi": "Malachi",
    "Matthew": "Matthew",
    "Mark": "Mark",
    "Luke": "Luke",
    "John": "John",
    "Acts": "Luke",
    "Romans": "Paul",
    "1 Corinthians": "Paul",
    "2 Corinthians": "Paul",
    "Galatians": "Paul",
    "Ephesians": "Paul",
    "Philippians": "Paul",
    "Colossians": "Paul",
    "1 Thessalonians": "Paul",
    "2 Thessalonians": "Paul",
    "1 Timothy": "Paul",
    "2 Timothy": "Paul",
    "Titus": "Paul",
    "Philemon": "Paul",
    "Hebrews": "Unknown",
    "James": "James",
    "1 Peter": "Peter",
    "2 Peter": "Peter",
    "1 John": "John",
    "2 John": "John",
    "3 John": "John",
    "Jude": "Jude",
    "Revelation": "John"
}

In [3]:
sept = loaders.load_sept()
tisch = loaders.load_tisch()
references = loaders.load_munged_references()

### Does Matthew Contain more OT references than John?

In [4]:
matthew_v_john = references[(references['n_start'].str[0] == "Matthew") | (references['n_start'].str[0] == "John")]
display(matthew_v_john.head(2))
display(matthew_v_john.tail(2))

,n_start,n_end,o_start,o_end,new_text,old_text
0,"(Matthew, 1, 1)","(Matthew, 1, 2)","(Genesis, 25, 19)","(Genesis, 25, 20)",βίβλος γενέσεως ἰησοῦ χριστοῦ υἱοῦ δαυεὶδ υἱοῦ...,και αυται αι γενεσεις ισαακ του υιου αβρααμ αβ...
1,"(Matthew, 1, 2)","(Matthew, 1, 3)","(Genesis, 44, 14)","(Genesis, 44, 14)",ἀβραὰμ ἐγέννησεν τὸν ἰσαάκ ἰσαὰκ δὲ ἐγέννησεν ...,εισηλθεν δε ιουδας και οι αδελφοι αυτου προς ι...

,n_start,n_end,o_start,o_end,new_text,old_text
2433,"(John, 21, 7)","(John, 21, 7)","(Job, 19, 6)","(Job, 19, 6)",λέγει οὖν ὁ μαθητὴς ἐκεῖνος ὃν ἠγάπα ὁ ἰησοῦς ...,γνωτε ουν οτι ο κυριος εστιν ο ταραξας οχυρωμα...
2434,"(John, 21, 13)","(John, 21, 13)","(2 Chronicles, 22, 11)","(2 Chronicles, 22, 11)",ἔρχεται ἰησοῦς καὶ λαμβάνει τὸν ἄρτον καὶ δίδω...,και ελαβεν ιωσαβεθ η θυγατηρ του βασιλεως τον ...

In [5]:
px.histogram(
    x = matthew_v_john['n_start'].str[0],
    labels = {'x':'', 'y':''},
    title = "Which has more Allusions, Matthew or John?"
)

In [6]:
matthew_v_john['n_start'].str[0].value_counts().to_frame()

         count
n_start
Matthew    660
John       322

#### Percentage of Author Allusions

In [7]:
fig = px.pie(
    references['n_start'].str[0].map(book_authors).value_counts().to_frame().reset_index(),
    names = "n_start",
    values= "count",
    title= "Percentage of references made by each Author in the NT."
)
fig.update_traces(textposition='inside', textinfo='percent+label', showlegend=False)
fig.show()

#### Most quoted old testatement texts

In [8]:
references['o_start'].str[0].map(book_authors)

0          Moses
1          Moses
2           Ezra
3           Ezra
4           Ezra
          ...
4802       Moses
4803      Joshua
4804        Ezra
4805        Ezra
4806    Jeremiah
Name: o_start, Length: 4807, dtype: object

In [9]:
ot_references = references['o_start'].str[0].value_counts().to_frame().reset_index()
rare_index = ot_references[ot_references['count'] < 12].index
ot_references.loc[rare_index, "o_start"] = "Other"
ot_references['color'] = ot_references['o_start'].apply(lambda book: "red" if book == "Other" else 'blue')
ot_references.head()

       o_start  count color
0       Psalms    812  blue
1      Genesis    553  blue
2  Deuteronomy    437  blue
3     Jeremiah    227  blue
4       Exodus    222  blue

In [10]:
fig = px.histogram(
    ot_references,
    x = "o_start",
    y = "count",
    color = "color",
    labels = {'x':'Old Testament Book', 'y':'Number of Allusions'},
    title = "Number of Times each Old Testament Book is Referenced."
)
fig.update_traces(showlegend=False)
fig.show()

#### Make a network.

In [11]:
import networkx as nx

In [12]:
revelations_references = references.query("n_start.str[0] == 'Revelation'").copy()
revelations_references

,n_start,n_end,o_start,o_end,new_text,old_text
3722,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 18)","(Ecclesiastes, 5, 18)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ιδου ο ειδον εγω αγαθον ο εστιν καλον του φαγε...
3723,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 19)","(Ecclesiastes, 5, 19)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,και γε πας ο ανθρωπος ω εδωκεν αυτω ο θεος πλο...
3724,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 6, 2)","(Ecclesiastes, 6, 2)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ανηρ ω δωσει αυτω ο θεος πλουτον και υπαρχοντα...
3725,"(Revelation, 1, 5)","(Revelation, 1, 5)","(Ezra, 7, 28)","(Ezra, 7, 28)",καὶ ἀπὸ ἰησοῦ χριστοῦ ὁ μάρτυς ὁ πιστός ὁ πρωτ...,και επ εμε εκλινεν ελεος εν οφθαλμοις του βασι...
3726,"(Revelation, 1, 6)","(Revelation, 1, 6)","(Psalms, 9, 5)","(Psalms, 9, 6)",καὶ ἐποίησεν ἡμᾶς βασιλείαν ἱερεῖς τῷ θεῷ καὶ ...,επετιμησας εθνεσιν και απωλετο ο ασεβης το ονο...
...,...,...,...,...,...,...
4802,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Deuteronomy, 30, 10)","(Deuteronomy, 30, 10)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,εαν εισακουσης της φωνης κυριου του θεου σου φ...
4803,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Joshua, 23, 6)","(Joshua, 23, 6)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,κατισχυσατε ουν σφοδρα φυλασσειν και ποιειν πα...
4804,"(Revelation, 22, 19)","(Revelation, 22, 20)","(2 Chronicles, 34, 21)","(2 Chronicles, 34, 22)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,πορευθητε ζητησατε τον κυριον περι εμου και πε...
4805,"(Revelation, 22, 19)","(Revelation, 22, 19)","(2 Chronicles, 34, 24)","(2 Chronicles, 34, 24)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,ουτως λεγει κυριος ιδου εγω επαγω κακα επι τον...
4806,"(Revelation, 22, 19)","(Revelation, 22, 20)","(Jeremiah, 25, 13)","(Jeremiah, 25, 15)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,και επαξω επι την γην εκεινην παντας τους λογο...

In [13]:
network = nx.DiGraph()
network.add_node('Revelation', type="NT")
network.add_nodes_from(
    list(set(revelations_references['o_start'].str[0])), type = "OT"
)

In [14]:
import networkx as nx

# Create an empty directed graph
G = nx.DiGraph()

# Add nodes
G.add_node('Revelation', type='NT')
G.add_nodes_from(
    list(set(revelations_references['o_start'].str[0])),
    type = "OT"
)

# Add edges (optionally with weight)
G.add_edge('Revelation', 'Genesis', weight=3)
G.add_edge('Revelation', 'Exodus', weight=2)
G.add_edge('Revelation', 'Daniel', weight=1)



pos = nx.spring_layout(G, seed=42)  # force-directed layout

import plotly.graph_objects as go

# Edges
edge_x, edge_y = [], []
for source, target in G.edges():
    x0, y0 = pos[source]
    x1, y1 = pos[target]
    edge_x.extend([x0, x1, None])
    edge_y.extend([y0, y1, None])

edge_trace = go.Scatter(x=edge_x, y=edge_y,
                        line=dict(width=2, color='gray'),
                        hoverinfo='none',
                        mode='lines')

# Nodes
node_x = [pos[node][0] for node in G.nodes()]
node_y = [pos[node][1] for node in G.nodes()]
node_trace = go.Scatter(x=node_x, y=node_y,
                        mode='markers+text',
                        text=list(G.nodes()),
                        textposition='top center',
                        marker=dict(size=20, color=['red' if G.nodes[n]['type']=='NT' else 'lightblue' for n in G.nodes()]))



fig = go.Figure(data=[edge_trace, node_trace])
fig.update_layout(
    xaxis=dict(showgrid=False, showticklabels=False, zeroline=False),
    yaxis=dict(showgrid=False, showticklabels=False, zeroline=False)
)
fig.show()

In [15]:
revelations_references

,n_start,n_end,o_start,o_end,new_text,old_text
3722,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 18)","(Ecclesiastes, 5, 18)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ιδου ο ειδον εγω αγαθον ο εστιν καλον του φαγε...
3723,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 19)","(Ecclesiastes, 5, 19)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,και γε πας ο ανθρωπος ω εδωκεν αυτω ο θεος πλο...
3724,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 6, 2)","(Ecclesiastes, 6, 2)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ανηρ ω δωσει αυτω ο θεος πλουτον και υπαρχοντα...
3725,"(Revelation, 1, 5)","(Revelation, 1, 5)","(Ezra, 7, 28)","(Ezra, 7, 28)",καὶ ἀπὸ ἰησοῦ χριστοῦ ὁ μάρτυς ὁ πιστός ὁ πρωτ...,και επ εμε εκλινεν ελεος εν οφθαλμοις του βασι...
3726,"(Revelation, 1, 6)","(Revelation, 1, 6)","(Psalms, 9, 5)","(Psalms, 9, 6)",καὶ ἐποίησεν ἡμᾶς βασιλείαν ἱερεῖς τῷ θεῷ καὶ ...,επετιμησας εθνεσιν και απωλετο ο ασεβης το ονο...
...,...,...,...,...,...,...
4802,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Deuteronomy, 30, 10)","(Deuteronomy, 30, 10)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,εαν εισακουσης της φωνης κυριου του θεου σου φ...
4803,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Joshua, 23, 6)","(Joshua, 23, 6)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,κατισχυσατε ουν σφοδρα φυλασσειν και ποιειν πα...
4804,"(Revelation, 22, 19)","(Revelation, 22, 20)","(2 Chronicles, 34, 21)","(2 Chronicles, 34, 22)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,πορευθητε ζητησατε τον κυριον περι εμου και πε...
4805,"(Revelation, 22, 19)","(Revelation, 22, 19)","(2 Chronicles, 34, 24)","(2 Chronicles, 34, 24)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,ουτως λεγει κυριος ιδου εγω επαγω κακα επι τον...
4806,"(Revelation, 22, 19)","(Revelation, 22, 20)","(Jeremiah, 25, 13)","(Jeremiah, 25, 15)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,και επαξω επι την γην εκεινην παντας τους λογο...

In [16]:
revelations_references['revelations_loc'] = revelations_references.apply(
    lambda row : (":".join(map(str, row['n_start'])) + "-" + str(row['n_end'][-1])),
    axis = 1,
)
revelations_references['old_testament_loc'] = revelations_references.apply(
    lambda row : (":".join(map(str, row['o_start'])) + "-" + str(row['o_start'][-1])),
    axis = 1,
)

revelations_references.head(3)

,n_start,n_end,o_start,o_end,new_text,old_text,revelations_loc,old_testament_loc
3722,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 18)","(Ecclesiastes, 5, 18)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ιδου ο ειδον εγω αγαθον ο εστιν καλον του φαγε...,Revelation:1:1-1,Ecclesiastes:5:18-18
3723,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 19)","(Ecclesiastes, 5, 19)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,και γε πας ο ανθρωπος ω εδωκεν αυτω ο θεος πλο...,Revelation:1:1-1,Ecclesiastes:5:19-19
3724,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 6, 2)","(Ecclesiastes, 6, 2)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ανηρ ω δωσει αυτω ο θεος πλουτον και υπαρχοντα...,Revelation:1:1-1,Ecclesiastes:6:2-2

In [17]:
len(list(set(revelations_references['old_testament_loc'])))

531

In [18]:
old_testament_books = revelations_references['o_start'].str[0].value_counts()
old_testament_books['Psalms']

323

In [19]:
G = nx.DiGraph()
G.add_node(
    "Revelation",
    type="NT"
)

old_testament_books = (revelations_references['o_start'].str[0]).value_counts()
G.add_nodes_from(
    old_testament_books.keys(),
    type = "OT"
)

for book in old_testament_books.items():
    G.add_edge(
        "Revelation",
        book[0],
        weight = book[1]
    )

In [20]:
import numpy as np
import networkx as nx
import plotly.graph_objects as go

# --- 1. Build the graph ---
G = nx.DiGraph()
G.add_node("Revelation", type="NT")

old_testament_books = dict((revelations_references['o_start'].str[0]).value_counts())

G.add_nodes_from(old_testament_books.keys(), type="OT")

for book, count in old_testament_books.items():
    G.add_edge("Revelation", book, weight=count)

# --- 2. Define layout (Revelation center, others around it) ---
center_node = "Revelation"
connected_nodes = list(G.neighbors(center_node))
pos = {center_node: (0, 0)}
radius = 1.8
n = len(connected_nodes)

for i, node in enumerate(connected_nodes):
    angle = 2 * np.pi * i / n
    pos[node] = (radius * np.cos(angle), radius * np.sin(angle))

# --- 3. Node sizes based on edge weights ---
weights = nx.get_edge_attributes(G, "weight")
max_w = max(weights.values()) if weights else 1
node_sizes = {
    node: 55 if node == center_node else 15 + 45 * (weights.get((center_node, node), 0) / max_w)
    for node in G.nodes
}

# --- 4. Build edge trace ---
edge_x, edge_y, edge_text = [], [], []
for src, dst, data in G.edges(data=True):
    x0, y0 = pos[src]
    x1, y1 = pos[dst]
    edge_x += [x0, x1, None]
    edge_y += [y0, y1, None]
    edge_text.append(f"{src} → {dst}: {data['weight']}")

edge_trace = go.Scatter(
    x=edge_x, y=edge_y,
    line=dict(width=1, color="#888"),
    hoverinfo="none",
    mode="lines"
)

# --- 5. Build node trace ---
node_x = [pos[node][0] for node in G.nodes]
node_y = [pos[node][1] for node in G.nodes]
node_text = [node for node in G.nodes]
node_size_list = [1.25 *node_sizes[node] for node in G.nodes]

node_trace = go.Scatter(
    x=node_x, y=node_y,
    mode="markers+text",
    text=node_text,
    textposition=[
        "middle center" if node == "Revelation" else "middle right"
        for node in G.nodes
    ],
    marker=dict(
        size=node_size_list,
        color=[
            "#f1c40f" if G.nodes[n]["type"] == "NT" else "#3498db"
            for n in G.nodes
        ],
        line=dict(width=2, color="#fff"),
        opacity=1,
    ),
    hovertext=[
        f"{node}: {weights.get((center_node, node), 0)} references" if node != center_node else node
        for node in G.nodes
    ],
    hoverinfo="text"
)

# --- 6. Plot ---
fig = go.Figure(data=[edge_trace, node_trace])
fig.update_layout(
    title=dict(
        text="All the References in Revelations",
        x=0.5,          # Center the title
        y=0.95,         # Raise it slightly above the plot
        xanchor='center',
        yanchor='top',
        font=dict(size=20)
    ),
    showlegend=False,
    margin=dict(l=40, r=40, t=80, b=40),  # add top margin for title
    plot_bgcolor="white",
    hovermode="closest",
    xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
    yaxis=dict(showgrid=False, zeroline=False, showticklabels=False)
)
fig.show()

#### Jesus in references

In [21]:
greek_words_for_jesus = [
    "Ἰησοῦς",   # Iesous – Jesus
    "Χριστός",  # Christos – Christ / Anointed One
    "Κύριος"    # Kyrios – Lord / Master
]

In [22]:
references

,n_start,n_end,o_start,o_end,new_text,old_text
0,"(Matthew, 1, 1)","(Matthew, 1, 2)","(Genesis, 25, 19)","(Genesis, 25, 20)",βίβλος γενέσεως ἰησοῦ χριστοῦ υἱοῦ δαυεὶδ υἱοῦ...,και αυται αι γενεσεις ισαακ του υιου αβρααμ αβ...
1,"(Matthew, 1, 2)","(Matthew, 1, 3)","(Genesis, 44, 14)","(Genesis, 44, 14)",ἀβραὰμ ἐγέννησεν τὸν ἰσαάκ ἰσαὰκ δὲ ἐγέννησεν ...,εισηλθεν δε ιουδας και οι αδελφοι αυτου προς ι...
2,"(Matthew, 1, 3)","(Matthew, 1, 3)","(1 Chronicles, 2, 4)","(1 Chronicles, 2, 4)",ἰούδας δὲ ἐγέννησεν τὸν φάρες καὶ τὸν ζάρα ἐκ ...,και θαμαρ η νυμφη αυτου ετεκεν αυτω τον φαρες ...
3,"(Matthew, 1, 11)","(Matthew, 1, 11)","(1 Chronicles, 26, 26)","(1 Chronicles, 26, 26)",ἰωσείας δὲ ἐγέννησεν τὸν ἰεχονίαν καὶ τοὺς ἀδε...,αυτος σαλωμωθ και οι αδελφοι αυτου επι παντων ...
4,"(Matthew, 1, 11)","(Matthew, 1, 11)","(1 Chronicles, 9, 32)","(1 Chronicles, 9, 32)",ἰωσείας δὲ ἐγέννησεν τὸν ἰεχονίαν καὶ τοὺς ἀδε...,και βαναιας ο κααθιτης εκ των αδελφων αυτων επ...
...,...,...,...,...,...,...
4802,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Deuteronomy, 30, 10)","(Deuteronomy, 30, 10)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,εαν εισακουσης της φωνης κυριου του θεου σου φ...
4803,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Joshua, 23, 6)","(Joshua, 23, 6)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,κατισχυσατε ουν σφοδρα φυλασσειν και ποιειν πα...
4804,"(Revelation, 22, 19)","(Revelation, 22, 20)","(2 Chronicles, 34, 21)","(2 Chronicles, 34, 22)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,πορευθητε ζητησατε τον κυριον περι εμου και πε...
4805,"(Revelation, 22, 19)","(Revelation, 22, 19)","(2 Chronicles, 34, 24)","(2 Chronicles, 34, 24)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,ουτως λεγει κυριος ιδου εγω επαγω κακα επι τον...
4806,"(Revelation, 22, 19)","(Revelation, 22, 20)","(Jeremiah, 25, 13)","(Jeremiah, 25, 15)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,και επαξω επι την γην εκεινην παντας τους λογο...

In [23]:
references['new_text'].str.contains("Ἰησοῦς", na=False).any()

False

In [24]:
matches = references[references['new_text'].str.contains("Ἐμμανουήλ", na=False)]
matches

Empty DataFrame
Columns: [n_start, n_end, o_start, o_end, new_text, old_text]
Index: []

#### Random

In [25]:
bible = loaders.load_bible()

In [ ]:
bible['text'].value_counts()

text
και               47452
εν                11109
καὶ                8930
του                8227
αυτου              7181
                  ...
αποβιαζου             1
προβαλλομενοις        1
αποκρινεσθαι          1
απογραψαι             1
ἀφελεῖ                1
Name: count, Length: 52740, dtype: int64

In [39]:
px.histogram(
    x = bible['text'].value_counts().keys()[:10],
    y = bible['text'].value_counts()[:10]
)