In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import loaders

In [ ]:
book_authors = {
    "Genesis": "Moses",
    "Exodus": "Moses",
    "Leviticus": "Moses",
    "Numbers": "Moses",
    "Deuteronomy": "Moses",
    "Joshua": "Joshua",
    "Judges": "Samuel; Nathan; Gad",
    "Ruth": "Samuel",
    "1 Samuel": "Samuel; Nathan; Gad",
    "2 Samuel": "Gad; Nathan",
    "1 Kings": "Jeremiah",
    "2 Kings": "Jeremiah",
    "1 Chronicles": "Ezra",
    "2 Chronicles": "Ezra",
    "Ezra": "Ezra",
    "Nehemiah": "Nehemiah",
    "Esther": "Mordecai",
    "Job": "Unknown",
    "Psalms": "David and others",
    "Proverbs": "Solomon; Agur; Lemuel",
    "Ecclesiastes": "Solomon",
    "Song of Songs": "Solomon",
    "Isaiah": "Isaiah",
    "Jeremiah": "Jeremiah",
    "Lamentations": "Jeremiah",
    "Ezekiel": "Ezekiel",
    "Daniel": "Daniel",
    "Hosea": "Hosea",
    "Joel": "Joel",
    "Amos": "Amos",
    "Obadiah": "Obadiah",
    "Jonah": "Jonah",
    "Micah": "Micah",
    "Nahum": "Nahum",
    "Habakkuk": "Habakkuk",
    "Zephaniah": "Zephaniah",
    "Haggai": "Haggai",
    "Zechariah": "Zechariah",
    "Malachi": "Malachi",
    "Matthew": "Matthew",
    "Mark": "Mark",
    "Luke": "Luke",
    "John": "John",
    "Acts": "Luke",
    "Romans": "Paul",
    "1 Corinthians": "Paul",
    "2 Corinthians": "Paul",
    "Galatians": "Paul",
    "Ephesians": "Paul",
    "Philippians": "Paul",
    "Colossians": "Paul",
    "1 Thessalonians": "Paul",
    "2 Thessalonians": "Paul",
    "1 Timothy": "Paul",
    "2 Timothy": "Paul",
    "Titus": "Paul",
    "Philemon": "Paul",
    "Hebrews": "Unknown",
    "James": "James",
    "1 Peter": "Peter",
    "2 Peter": "Peter",
    "1 John": "John",
    "2 John": "John",
    "3 John": "John",
    "Jude": "Jude",
    "Revelation": "John",
}

In [ ]:
sept = loaders.load_sept()
tisch = loaders.load_tisch()
references = loaders.load_munged_references()

### Does Matthew Contain more OT references than John?

In [ ]:
matthew_v_john = references[
    (references["n_start"].str[0] == "Matthew")
    | (references["n_start"].str[0] == "John")
]
display(matthew_v_john.head(2))
display(matthew_v_john.tail(2))

,n_start,n_end,o_start,o_end,new_text,old_text
0,"(Matthew, 1, 1)","(Matthew, 1, 2)","(Genesis, 25, 19)","(Genesis, 25, 20)",βίβλος γενέσεως ἰησοῦ χριστοῦ υἱοῦ δαυεὶδ υἱοῦ...,και αυται αι γενεσεις ισαακ του υιου αβρααμ αβ...
1,"(Matthew, 1, 2)","(Matthew, 1, 3)","(Genesis, 44, 14)","(Genesis, 44, 14)",ἀβραὰμ ἐγέννησεν τὸν ἰσαάκ ἰσαὰκ δὲ ἐγέννησεν ...,εισηλθεν δε ιουδας και οι αδελφοι αυτου προς ι...

,n_start,n_end,o_start,o_end,new_text,old_text
2433,"(John, 21, 7)","(John, 21, 7)","(Job, 19, 6)","(Job, 19, 6)",λέγει οὖν ὁ μαθητὴς ἐκεῖνος ὃν ἠγάπα ὁ ἰησοῦς ...,γνωτε ουν οτι ο κυριος εστιν ο ταραξας οχυρωμα...
2434,"(John, 21, 13)","(John, 21, 13)","(2 Chronicles, 22, 11)","(2 Chronicles, 22, 11)",ἔρχεται ἰησοῦς καὶ λαμβάνει τὸν ἄρτον καὶ δίδω...,και ελαβεν ιωσαβεθ η θυγατηρ του βασιλεως τον ...

In [ ]:
px.histogram(
    x=matthew_v_john["n_start"].str[0],
    labels={"x": "", "y": ""},
    title="Which has more Allusions, Matthew or John?",
)

In [ ]:
matthew_v_john["n_start"].str[0].value_counts().to_frame()

         count
n_start
Matthew    660
John       322

#### Percentage of Author Allusions

In [ ]:
fig = px.pie(
    references["n_start"]
    .str[0]
    .map(book_authors)
    .value_counts()
    .to_frame()
    .reset_index(),
    names="n_start",
    values="count",
    title="Percentage of references made by each Author in the NT.",
)
fig.update_traces(textposition="inside", textinfo="percent+label", showlegend=False)
fig.show()

#### Most quoted old testatement texts

In [ ]:
references["o_start"].str[0].map(book_authors)

0          Moses
1          Moses
2           Ezra
3           Ezra
4           Ezra
          ...
4802       Moses
4803      Joshua
4804        Ezra
4805        Ezra
4806    Jeremiah
Name: o_start, Length: 4807, dtype: object

In [ ]:
ot_references = references["o_start"].str[0].value_counts().to_frame().reset_index()
rare_index = ot_references[ot_references["count"] < 12].index
ot_references.loc[rare_index, "o_start"] = "Other"
ot_references["color"] = ot_references["o_start"].apply(
    lambda book: "red" if book == "Other" else "blue"
)
ot_references.head()

       o_start  count color
0       Psalms    812  blue
1      Genesis    553  blue
2  Deuteronomy    437  blue
3     Jeremiah    227  blue
4       Exodus    222  blue

In [ ]:
fig = px.histogram(
    ot_references,
    x="o_start",
    y="count",
    color="color",
    labels={"x": "Old Testament Book", "y": "Number of Allusions"},
    title="Number of Times each Old Testament Book is Referenced.",
)
fig.update_traces(showlegend=False)
fig.show()

#### Make a network.

In [ ]:
import networkx as nx

In [ ]:
revelations_references = references.query("n_start.str[0] == 'Revelation'").copy()
revelations_references

,n_start,n_end,o_start,o_end,new_text,old_text
3722,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 18)","(Ecclesiastes, 5, 18)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ιδου ο ειδον εγω αγαθον ο εστιν καλον του φαγε...
3723,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 19)","(Ecclesiastes, 5, 19)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,και γε πας ο ανθρωπος ω εδωκεν αυτω ο θεος πλο...
3724,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 6, 2)","(Ecclesiastes, 6, 2)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ανηρ ω δωσει αυτω ο θεος πλουτον και υπαρχοντα...
3725,"(Revelation, 1, 5)","(Revelation, 1, 5)","(Ezra, 7, 28)","(Ezra, 7, 28)",καὶ ἀπὸ ἰησοῦ χριστοῦ ὁ μάρτυς ὁ πιστός ὁ πρωτ...,και επ εμε εκλινεν ελεος εν οφθαλμοις του βασι...
3726,"(Revelation, 1, 6)","(Revelation, 1, 6)","(Psalms, 9, 5)","(Psalms, 9, 6)",καὶ ἐποίησεν ἡμᾶς βασιλείαν ἱερεῖς τῷ θεῷ καὶ ...,επετιμησας εθνεσιν και απωλετο ο ασεβης το ονο...
...,...,...,...,...,...,...
4802,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Deuteronomy, 30, 10)","(Deuteronomy, 30, 10)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,εαν εισακουσης της φωνης κυριου του θεου σου φ...
4803,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Joshua, 23, 6)","(Joshua, 23, 6)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,κατισχυσατε ουν σφοδρα φυλασσειν και ποιειν πα...
4804,"(Revelation, 22, 19)","(Revelation, 22, 20)","(2 Chronicles, 34, 21)","(2 Chronicles, 34, 22)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,πορευθητε ζητησατε τον κυριον περι εμου και πε...
4805,"(Revelation, 22, 19)","(Revelation, 22, 19)","(2 Chronicles, 34, 24)","(2 Chronicles, 34, 24)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,ουτως λεγει κυριος ιδου εγω επαγω κακα επι τον...
4806,"(Revelation, 22, 19)","(Revelation, 22, 20)","(Jeremiah, 25, 13)","(Jeremiah, 25, 15)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,και επαξω επι την γην εκεινην παντας τους λογο...

In [ ]:
network = nx.DiGraph()
network.add_node("Revelation", type="NT")
network.add_nodes_from(list(set(revelations_references["o_start"].str[0])), type="OT")

In [ ]:
import networkx as nx

# Create an empty directed graph
G = nx.DiGraph()

# Add nodes
G.add_node("Revelation", type="NT")
G.add_nodes_from(list(set(revelations_references["o_start"].str[0])), type="OT")

# Add edges (optionally with weight)
G.add_edge("Revelation", "Genesis", weight=3)
G.add_edge("Revelation", "Exodus", weight=2)
G.add_edge("Revelation", "Daniel", weight=1)


pos = nx.spring_layout(G, seed=42)  # force-directed layout

import plotly.graph_objects as go

# Edges
edge_x, edge_y = [], []
for source, target in G.edges():
    x0, y0 = pos[source]
    x1, y1 = pos[target]
    edge_x.extend([x0, x1, None])
    edge_y.extend([y0, y1, None])

edge_trace = go.Scatter(
    x=edge_x, y=edge_y, line=dict(width=2, color="gray"), hoverinfo="none", mode="lines"
)

# Nodes
node_x = [pos[node][0] for node in G.nodes()]
node_y = [pos[node][1] for node in G.nodes()]
node_trace = go.Scatter(
    x=node_x,
    y=node_y,
    mode="markers+text",
    text=list(G.nodes()),
    textposition="top center",
    marker=dict(
        size=20,
        color=["red" if G.nodes[n]["type"] == "NT" else "lightblue" for n in G.nodes()],
    ),
)


fig = go.Figure(data=[edge_trace, node_trace])
fig.update_layout(
    xaxis=dict(showgrid=False, showticklabels=False, zeroline=False),
    yaxis=dict(showgrid=False, showticklabels=False, zeroline=False),
)
fig.show()

In [ ]:
revelations_references

,n_start,n_end,o_start,o_end,new_text,old_text
3722,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 18)","(Ecclesiastes, 5, 18)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ιδου ο ειδον εγω αγαθον ο εστιν καλον του φαγε...
3723,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 19)","(Ecclesiastes, 5, 19)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,και γε πας ο ανθρωπος ω εδωκεν αυτω ο θεος πλο...
3724,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 6, 2)","(Ecclesiastes, 6, 2)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ανηρ ω δωσει αυτω ο θεος πλουτον και υπαρχοντα...
3725,"(Revelation, 1, 5)","(Revelation, 1, 5)","(Ezra, 7, 28)","(Ezra, 7, 28)",καὶ ἀπὸ ἰησοῦ χριστοῦ ὁ μάρτυς ὁ πιστός ὁ πρωτ...,και επ εμε εκλινεν ελεος εν οφθαλμοις του βασι...
3726,"(Revelation, 1, 6)","(Revelation, 1, 6)","(Psalms, 9, 5)","(Psalms, 9, 6)",καὶ ἐποίησεν ἡμᾶς βασιλείαν ἱερεῖς τῷ θεῷ καὶ ...,επετιμησας εθνεσιν και απωλετο ο ασεβης το ονο...
...,...,...,...,...,...,...
4802,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Deuteronomy, 30, 10)","(Deuteronomy, 30, 10)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,εαν εισακουσης της φωνης κυριου του θεου σου φ...
4803,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Joshua, 23, 6)","(Joshua, 23, 6)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,κατισχυσατε ουν σφοδρα φυλασσειν και ποιειν πα...
4804,"(Revelation, 22, 19)","(Revelation, 22, 20)","(2 Chronicles, 34, 21)","(2 Chronicles, 34, 22)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,πορευθητε ζητησατε τον κυριον περι εμου και πε...
4805,"(Revelation, 22, 19)","(Revelation, 22, 19)","(2 Chronicles, 34, 24)","(2 Chronicles, 34, 24)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,ουτως λεγει κυριος ιδου εγω επαγω κακα επι τον...
4806,"(Revelation, 22, 19)","(Revelation, 22, 20)","(Jeremiah, 25, 13)","(Jeremiah, 25, 15)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,και επαξω επι την γην εκεινην παντας τους λογο...

In [ ]:
revelations_references["revelations_loc"] = revelations_references.apply(
    lambda row: (":".join(map(str, row["n_start"])) + "-" + str(row["n_end"][-1])),
    axis=1,
)
revelations_references["old_testament_loc"] = revelations_references.apply(
    lambda row: (":".join(map(str, row["o_start"])) + "-" + str(row["o_start"][-1])),
    axis=1,
)

revelations_references.head(3)

,n_start,n_end,o_start,o_end,new_text,old_text,revelations_loc,old_testament_loc
3722,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 18)","(Ecclesiastes, 5, 18)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ιδου ο ειδον εγω αγαθον ο εστιν καλον του φαγε...,Revelation:1:1-1,Ecclesiastes:5:18-18
3723,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 5, 19)","(Ecclesiastes, 5, 19)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,και γε πας ο ανθρωπος ω εδωκεν αυτω ο θεος πλο...,Revelation:1:1-1,Ecclesiastes:5:19-19
3724,"(Revelation, 1, 1)","(Revelation, 1, 1)","(Ecclesiastes, 6, 2)","(Ecclesiastes, 6, 2)",ἀποκάλυψις ἰησοῦ χριστοῦ ἣν ἔδωκεν αὐτῷ ὁ θεός...,ανηρ ω δωσει αυτω ο θεος πλουτον και υπαρχοντα...,Revelation:1:1-1,Ecclesiastes:6:2-2

In [ ]:
len(list(set(revelations_references["old_testament_loc"])))

531

In [ ]:
old_testament_books = revelations_references["o_start"].str[0].value_counts()
old_testament_books["Psalms"]

323

In [ ]:
G = nx.DiGraph()
G.add_node("Revelation", type="NT")

old_testament_books = (revelations_references["o_start"].str[0]).value_counts()
G.add_nodes_from(old_testament_books.keys(), type="OT")

for book in old_testament_books.items():
    G.add_edge("Revelation", book[0], weight=book[1])

In [ ]:
import numpy as np
import networkx as nx
import plotly.graph_objects as go

# --- 1. Build the graph ---
G = nx.DiGraph()
G.add_node("Revelation", type="NT")

old_testament_books = dict((revelations_references["o_start"].str[0]).value_counts())

G.add_nodes_from(old_testament_books.keys(), type="OT")

for book, count in old_testament_books.items():
    G.add_edge("Revelation", book, weight=count)

# --- 2. Define layout (Revelation center, others around it) ---
center_node = "Revelation"
connected_nodes = list(G.neighbors(center_node))
pos = {center_node: (0, 0)}
radius = 1.8
n = len(connected_nodes)

for i, node in enumerate(connected_nodes):
    angle = 2 * np.pi * i / n
    pos[node] = (radius * np.cos(angle), radius * np.sin(angle))

# --- 3. Node sizes based on edge weights ---
weights = nx.get_edge_attributes(G, "weight")
max_w = max(weights.values()) if weights else 1
node_sizes = {
    node: 55
    if node == center_node
    else 15 + 45 * (weights.get((center_node, node), 0) / max_w)
    for node in G.nodes
}

# --- 4. Build edge trace ---
edge_x, edge_y, edge_text = [], [], []
for src, dst, data in G.edges(data=True):
    x0, y0 = pos[src]
    x1, y1 = pos[dst]
    edge_x += [x0, x1, None]
    edge_y += [y0, y1, None]
    edge_text.append(f"{src} → {dst}: {data['weight']}")

edge_trace = go.Scatter(
    x=edge_x, y=edge_y, line=dict(width=1, color="#888"), hoverinfo="none", mode="lines"
)

# --- 5. Build node trace ---
node_x = [pos[node][0] for node in G.nodes]
node_y = [pos[node][1] for node in G.nodes]
node_text = [node for node in G.nodes]
node_size_list = [1.25 * node_sizes[node] for node in G.nodes]

node_trace = go.Scatter(
    x=node_x,
    y=node_y,
    mode="markers+text",
    text=node_text,
    textposition=[
        "middle center" if node == "Revelation" else "middle right" for node in G.nodes
    ],
    marker=dict(
        size=node_size_list,
        color=["#f1c40f" if G.nodes[n]["type"] == "NT" else "#3498db" for n in G.nodes],
        line=dict(width=2, color="#fff"),
        opacity=1,
    ),
    hovertext=[
        f"{node}: {weights.get((center_node, node), 0)} references"
        if node != center_node
        else node
        for node in G.nodes
    ],
    hoverinfo="text",
)

# --- 6. Plot ---
fig = go.Figure(data=[edge_trace, node_trace])
fig.update_layout(
    title=dict(
        text="All the References in Revelations",
        x=0.5,  # Center the title
        y=0.95,  # Raise it slightly above the plot
        xanchor="center",
        yanchor="top",
        font=dict(size=20),
    ),
    showlegend=False,
    margin=dict(l=40, r=40, t=80, b=40),  # add top margin for title
    plot_bgcolor="white",
    hovermode="closest",
    xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
    yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
)
fig.show()

#### Jesus in references

In [ ]:
greek_words_for_jesus = [
    "Ἰησοῦς",  # Iesous – Jesus
    "Χριστός",  # Christos – Christ / Anointed One
    "Κύριος",  # Kyrios – Lord / Master
]

In [ ]:
references

,n_start,n_end,o_start,o_end,new_text,old_text
0,"(Matthew, 1, 1)","(Matthew, 1, 2)","(Genesis, 25, 19)","(Genesis, 25, 20)",βίβλος γενέσεως ἰησοῦ χριστοῦ υἱοῦ δαυεὶδ υἱοῦ...,και αυται αι γενεσεις ισαακ του υιου αβρααμ αβ...
1,"(Matthew, 1, 2)","(Matthew, 1, 3)","(Genesis, 44, 14)","(Genesis, 44, 14)",ἀβραὰμ ἐγέννησεν τὸν ἰσαάκ ἰσαὰκ δὲ ἐγέννησεν ...,εισηλθεν δε ιουδας και οι αδελφοι αυτου προς ι...
2,"(Matthew, 1, 3)","(Matthew, 1, 3)","(1 Chronicles, 2, 4)","(1 Chronicles, 2, 4)",ἰούδας δὲ ἐγέννησεν τὸν φάρες καὶ τὸν ζάρα ἐκ ...,και θαμαρ η νυμφη αυτου ετεκεν αυτω τον φαρες ...
3,"(Matthew, 1, 11)","(Matthew, 1, 11)","(1 Chronicles, 26, 26)","(1 Chronicles, 26, 26)",ἰωσείας δὲ ἐγέννησεν τὸν ἰεχονίαν καὶ τοὺς ἀδε...,αυτος σαλωμωθ και οι αδελφοι αυτου επι παντων ...
4,"(Matthew, 1, 11)","(Matthew, 1, 11)","(1 Chronicles, 9, 32)","(1 Chronicles, 9, 32)",ἰωσείας δὲ ἐγέννησεν τὸν ἰεχονίαν καὶ τοὺς ἀδε...,και βαναιας ο κααθιτης εκ των αδελφων αυτων επ...
...,...,...,...,...,...,...
4802,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Deuteronomy, 30, 10)","(Deuteronomy, 30, 10)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,εαν εισακουσης της φωνης κυριου του θεου σου φ...
4803,"(Revelation, 22, 19)","(Revelation, 22, 19)","(Joshua, 23, 6)","(Joshua, 23, 6)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,κατισχυσατε ουν σφοδρα φυλασσειν και ποιειν πα...
4804,"(Revelation, 22, 19)","(Revelation, 22, 20)","(2 Chronicles, 34, 21)","(2 Chronicles, 34, 22)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,πορευθητε ζητησατε τον κυριον περι εμου και πε...
4805,"(Revelation, 22, 19)","(Revelation, 22, 19)","(2 Chronicles, 34, 24)","(2 Chronicles, 34, 24)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,ουτως λεγει κυριος ιδου εγω επαγω κακα επι τον...
4806,"(Revelation, 22, 19)","(Revelation, 22, 20)","(Jeremiah, 25, 13)","(Jeremiah, 25, 15)",καὶ ἐάν τις ἀφέλῃ ἀπὸ τῶν λόγων τοῦ βιβλίου τῆ...,και επαξω επι την γην εκεινην παντας τους λογο...

In [ ]:
references["new_text"].str.contains("Ἰησοῦς", na=False).any()

False

In [ ]:
matches = references[references["new_text"].str.contains("Ἐμμανουήλ", na=False)]
matches

Empty DataFrame
Columns: [n_start, n_end, o_start, o_end, new_text, old_text]
Index: []

#### Random

In [ ]:
bible = loaders.load_bible()

In [ ]:
total_verses = bible[["book", "chapter", "verse"]].drop_duplicates().shape[0]
print(total_verses)

30782

In [ ]:
px.histogram(
    x=bible["text"].value_counts().keys()[:10], y=bible["text"].value_counts()[:10]
)

In [ ]:
words2 = pd.concat([sept, tisch])
words2["text"].value_counts()

text
και               47452
εν                11109
καὶ                8930
του                8227
αυτου              7181
                  ...
αποβιαζου             1
προβαλλομενοις        1
αποκρινεσθαι          1
απογραψαι             1
ἀφελεῖ                1
Name: count, Length: 52740, dtype: int64

In [ ]:
top15 = words2["text"].value_counts()[:100]

In [ ]:
top15

text
και      47452
εν       11109
καὶ       8930
του       8227
αυτου     7181
         ...
τὰ         828
ει         800
ταις       775
τουτο      768
ημερα      758
Name: count, Length: 100, dtype: int64

In [ ]:
words2["pos"] = words2["rmac"].str[0]

In [ ]:
individual_words = words2.drop_duplicates(subset="text")
top_words = individual_words[individual_words["text"].isin(top15.index)]
top_words["rmac"].value_counts()

rmac
prep        14
conj         8
n-nsm        4
p-gp         2
p-as         2
p-ns         2
t-npm        2
p-gs         2
t-apn        2
t-dsf        2
n-pri        2
t-nsm        2
prt-n        2
n-gsm        2
t-gsf        2
adv          2
prt          2
t-nsf        2
t-asf        2
t-asm        2
p-ds         2
i-asn        1
d-asn        1
d-dsf        1
n-npm        1
v-pai-2s     1
t-npf        1
d-dpm        1
p-gsm        1
t-gsm        1
t-dsm        1
p-dsm        1
t-nsn        1
d-asf        1
d-asm        1
t-dpn        1
v-fmi-3s     1
n-asf        1
v-iai-3s     1
t-gsn        1
v-aai-3s     1
t-asn        1
n-nsf        1
t-apf        1
d-gpm        1
t-gpn        1
r-gsm        1
d-gsn        1
d-dsm        1
n-gsf        1
t-dsn        1
t-apm        1
d-apm        1
t-dpf        1
a-apn        1
d-gsf        1
inj          1
v-pai-3s     1
t-gpf        1
Name: count, dtype: int64

In [ ]:
px.histogram(top_words, x="rmac")

In [ ]:
rmac = pd.read_pickle("./pickles/rmac_df")

In [ ]:
top15

text
και      47452
εν       11109
καὶ       8930
του       8227
αυτου     7181
ο         7129
σου       5715
εις       5689
τον       5573
την       5487
Name: count, dtype: int64

In [ ]:
pd.read_pickle("./pickles/references-naive.pickle")

[(481601, 5, 178, 5),
 (481602, 5, 179, 5),
 (479354, 5, 574, 5),
 (482957, 5, 575, 5),
 (486353, 5, 607, 5),
 (479354, 5, 633, 5),
 (482957, 5, 634, 5),
 (482957, 5, 695, 5),
 (493213, 5, 1033, 5),
 (482957, 5, 1113, 5),
 (482957, 5, 1148, 5),
 (486360, 5, 1234, 5),
 (476071, 5, 1240, 5),
 (476218, 5, 1240, 5),
 (476241, 5, 1240, 5),
 (486370, 5, 1247, 5),
 (486371, 5, 1248, 5),
 (486372, 5, 1249, 5),
 (486373, 5, 1250, 5),
 (486374, 5, 1251, 5),
 (478540, 5, 2029, 5),
 (486353, 5, 2402, 5),
 (484843, 5, 2883, 5),
 (478361, 5, 3035, 5),
 (479354, 5, 3861, 5),
 (482957, 5, 3862, 5),
 (477465, 5, 3915, 5),
 (481593, 5, 5526, 5),
 (476376, 5, 6666, 5),
 (476376, 5, 6701, 5),
 (476377, 5, 6702, 5),
 (486113, 5, 7207, 5),
 (475784, 5, 7980, 5),
 (475785, 5, 7981, 5),
 (475786, 5, 7982, 5),
 (475787, 5, 7983, 5),
 (475788, 5, 7984, 5),
 (475827, 5, 7984, 5),
 (475750, 5, 7985, 5),
 (475789, 5, 7985, 5),
 (475828, 5, 7985, 5),
 (475751, 5, 7986, 5),
 (475790, 5, 7986, 5),
 (475829, 5, 7986, 5),
 (475750, 5, 8496, 5),
 (475789, 5, 8496, 5),
 (475828, 5, 8496, 5),
 (475751, 5, 8497, 5),
 (475790, 5, 8497, 5),
 (475829, 5, 8497, 5),
 (485547, 5, 9395, 5),
 (475750, 5, 10194, 5),
 (475789, 5, 10194, 5),
 (475828, 5, 10194, 5),
 (475751, 5, 10195, 5),
 (475790, 5, 10195, 5),
 (475829, 5, 10195, 5),
 (475750, 5, 10218, 5),
 (475789, 5, 10218, 5),
 (475828, 5, 10218, 5),
 (475751, 5, 10219, 5),
 (475790, 5, 10219, 5),
 (475829, 5, 10219, 5),
 (484216, 5, 12067, 5),
 (484216, 5, 12242, 5),
 (489995, 5, 13187, 5),
 (476071, 5, 13547, 5),
 (476218, 5, 13547, 5),
 (476241, 5, 13547, 5),
 (475406, 5, 14160, 5),
 (475407, 5, 14161, 5),
 (475751, 5, 14311, 5),
 (475790, 5, 14311, 5),
 (475829, 5, 14311, 5),
 (483959, 5, 14625, 5),
 (488682, 5, 14976, 5),
 (484043, 5, 16399, 5),
 (486363, 5, 16399, 5),
 (486605, 5, 16399, 5),
 (476071, 5, 16401, 5),
 (476218, 5, 16401, 5),
 (476241, 5, 16401, 5),
 (476219, 5, 16402, 5),
 (476220, 5, 16403, 5),
 (483594, 5, 16990, 5),
 (475751, 5, 17650, 5),
 (475790, 5, 17650, 5),
 (475829, 5, 17650, 5),
 (475751, 5, 17725, 5),
 (475790, 5, 17725, 5),
 (475829, 5, 17725, 5),
 (475751, 5, 17865, 5),
 (475790, 5, 17865, 5),
 (475829, 5, 17865, 5),
 (475751, 5, 17907, 5),
 (475790, 5, 17907, 5),
 (475829, 5, 17907, 5),
 (475751, 5, 17918, 5),
 (475790, 5, 17918, 5),
 (475829, 5, 17918, 5),
 (475751, 5, 17955, 5),
 (475790, 5, 17955, 5),
 (475829, 5, 17955, 5),
 (493496, 5, 17980, 5),
 (478563, 5, 18661, 5),
 (478564, 5, 18662, 5),
 (476944, 5, 18952, 5),
 (488684, 5, 19613, 5),
 (488685, 5, 19614, 5),
 (488607, 5, 20068, 5),
 (488608, 5, 20069, 5),
 (476503, 5, 21589, 5),
 (493630, 5, 22158, 5),
 (482300, 5, 22980, 5),
 (482301, 5, 22981, 5),
 (482302, 5, 22982, 5),
 (475788, 5, 23566, 5),
 (475827, 5, 23566, 5),
 (475750, 5, 23567, 5),
 (475789, 5, 23567, 5),
 (475828, 5, 23567, 5),
 (475751, 5, 23568, 5),
 (475790, 5, 23568, 5),
 (475829, 5, 23568, 5),
 (475788, 5, 23577, 5),
 (475827, 5, 23577, 5),
 (475750, 5, 23578, 5),
 (475789, 5, 23578, 5),
 (475828, 5, 23578, 5),
 (475751, 5, 23579, 5),
 (475790, 5, 23579, 5),
 (475829, 5, 23579, 5),
 (475788, 5, 23588, 5),
 (475827, 5, 23588, 5),
 (475750, 5, 23589, 5),
 (475789, 5, 23589, 5),
 (475828, 5, 23589, 5),
 (475751, 5, 23590, 5),
 (475790, 5, 23590, 5),
 (475829, 5, 23590, 5),
 (488577, 5, 23642, 5),
 (488578, 5, 23643, 5),
 (475751, 5, 24168, 5),
 (475790, 5, 24168, 5),
 (475829, 5, 24168, 5),
 (475751, 5, 24190, 5),
 (475790, 5, 24190, 5),
 (475829, 5, 24190, 5),
 (476503, 5, 24252, 5),
 (480669, 5, 24388, 5),
 (476503, 5, 24520, 5),
 (477465, 5, 24879, 5),
 (479354, 5, 25117, 5),
 (485720, 5, 26064, 5),
 (479384, 5, 26258, 5),
 (482302, 5, 26713, 5),
 (476503, 5, 27512, 5),
 (475421, 5, 28268, 5),
 (488681, 5, 29393, 5),
 (491891, 5, 29428, 5),
 (482342, 5, 30030, 5),
 (482302, 5, 30177, 5),
 (482303, 5, 30178, 5),
 (482302, 5, 30199, 5),
 (492756, 5, 31328, 5),
 (479205, 5, 32522, 5),
 (479205, 5, 33485, 5),
 (479205, 5, 35355, 5),
 (479205, 5, 35485, 5),
 (479709, 5, 36522, 5),
 (488742, 5, 37195, 5),
 (476503, 5, 41833, 5),
 (493630, 5, 43286, 5),
 (486113, 5, 43315, 5),
 (477053, 5, 44054, 5),
 (491095, 5, 44360, 5),
 (481358, 5, 44549, 5),
 (486113, 5, 44938, 5),
 (481109, 5, 46450, 5),
 (481110, 5, 46451, 5),
 (481111, 5, 46452, 5),
 (481112, 5, 46453, 5),
 (486778, 5, 46900, 5),
 (486779, 5, 46901, 5),
 (484421, 5, 47188, 5),
 (477053, 5, 47189, 5),
 (492756, 5, 50006, 5),
 (492756, 5, 50028, 5),
 (492463, 5, 51275, 5),
 (492464, 5, 51276, 5),
 (481358, 5, 51972, 5),
 (479205, 5, 52294, 5),
 (479205, 5, 52843, 5),
 (481111, 5, 52856, 5),
 (481112, 5, 52857, 5),
 (492756, 5, 57596, 5),
 (492756, 5, 58371, 5),
 (486544, 5, 58554, 5),
 (487462, 5, 60145, 5),
 (487462, 5, 61370, 5),
 (487462, 5, 61389, 5),
 (492756, 5, 61409, 5),
 (486610, 5, 70186, 5),
 (484076, 5, 70765, 5),
 (484077, 5, 70766, 5),
 (484078, 5, 70767, 5),
 (492756, 5, 73437, 5),
 (479078, 5, 80298, 5),
 (479079, 5, 80299, 5),
 (476944, 5, 83164, 5),
 (475885, 5, 83721, 5),
 (492194, 5, 85377, 5),
 (484421, 5, 85596, 5),
 (477053, 5, 85597, 5),
 (485243, 5, 88187, 5),
 (485243, 5, 88673, 5),
 (493213, 5, 88854, 5),
 (492463, 5, 88900, 5),
 (482302, 5, 89094, 5),
 (484216, 5, 90190, 5),
 (476503, 5, 91956, 5),
 (476503, 5, 92305, 5),
 (476503, 5, 92503, 5),
 (479945, 5, 95525, 5),
 (479946, 5, 95526, 5),
 (479947, 5, 95527, 5),
 (486544, 5, 95621, 5),
 (476503, 5, 97483, 5),
 (483429, 5, 97568, 5),
 (489771, 5, 97569, 5),
 (479205, 5, 98616, 5),
 (484142, 5, 98887, 5),
 (479205, 5, 101693, 5),
 (477053, 5, 102039, 5),
 (477053, 5, 102403, 5),
 (477053, 5, 102446, 5),
 (486113, 5, 103491, 5),
 (488742, 5, 104293, 5),
 (488747, 5, 104779, 5),
 (488741, 5, 106175, 5),
 (488747, 5, 106181, 5),
 (488753, 5, 106187, 5),
 (488748, 5, 106208, 5),
 (479205, 5, 106283, 5),
 (488742, 5, 106369, 5),
 (488742, 5, 106378, 5),
 (476737, 5, 106392, 5),
 (488742, 5, 107155, 5),
 (479709, 5, 107281, 5),
 (488742, 5, 107335, 5),
 (476667, 5, 107385, 5),
 (476668, 5, 107386, 5),
 (476669, 5, 107387, 5),
 (476670, 5, 107388, 5),
 (476671, 5, 107389, 5),
 (476672, 5, 107390, 5),
 (476782, 5, 107456, 5),
 (488742, 5, 107985, 5),
 (479205, 5, 108498, 5),
 (482587, 5, 108515, 5),
 (484421, 5, 108651, 5),
 (477053, 5, 108652, 5),
 (488747, 5, 108884, 5),
 (476782, 5, 108971, 5),
 (488741, 5, 109092, 5),
 (488741, 5, 109417, 5),
 (488747, 5, 109426, 5),
 (488753, 5, 109432, 5),
 (489564, 5, 109943, 5),
 (488742, 5, 110004, 5),
 (488741, 5, 110878, 5),
 (488747, 5, 110884, 5),
 (488742, 5, 111646, 5),
 (488742, 5, 111878, 5),
 (488742, 5, 111949, 5),
 (488742, 5, 112144, 5),
 (488742, 5, 112352, 5),
 (488742, 5, 112437, 5),
 (488742, 5, 112859, 5),
 (488742, 5, 112878, 5),
 (488742, 5, 112906, 5),
 (482366, 5, 113366, 5),
 (488742, 5, 113899, 5),
 (485696, 5, 113977, 5),
 (488741, 5, 114309, 5),
 (485953, 5, 114485, 5),
 (482366, 5, 114520, 5),
 (484043, 5, 115397, 5),
 (486363, 5, 115397, 5),
 (486605, 5, 115397, 5),
 (476071, 5, 115545, 5),
 (476218, 5, 115545, 5),
 (476241, 5, 115545, 5),
 (488742, 5, 116719, 5),
 (489770, 5, 116877, 5),
 (488742, 5, 117284, 5),
 (492194, 5, 117588, 5),
 (492195, 5, 117589, 5),
 (475751, 5, 117608, 5),
 (475790, 5, 117608, 5),
 (475829, 5, 117608, 5),
 (482366, 5, 117878, 5),
 (488747, 5, 118285, 5),
 (482957, 5, 119465, 5),
 (488742, 5, 119894, 5),
 (488742, 5, 120069, 5),
 (493630, 5, 120195, 5),
 (479205, 5, 120833, 5),
 (488747, 5, 121314, 5),
 (488753, 5, 121320, 5),
 (488741, 5, 121417, 5),
 (488747, 5, 121423, 5),
 (488742, 5, 121481, 5),
 (488747, 5, 121567, 5),
 (488748, 5, 121651, 5),
 (488741, 5, 121690, 5),
 (488742, 5, 121717, 5),
 (488741, 5, 121811, 5),
 (479205, 5, 121845, 5),
 (488742, 5, 122099, 5),
 (486113, 5, 122126, 5),
 (484043, 5, 123854, 5),
 (486363, 5, 123854, 5),
 (486605, 5, 123854, 5),
 (479205, 5, 124330, 5),
 (482340, 5, 125251, 5),
 (482341, 5, 125252, 5),
 (482342, 5, 125253, 5),
 (482300, 5, 125384, 5),
 (482301, 5, 125385, 5),
 (482302, 5, 125386, 5),
 (486778, 5, 126072, 5),
 (476110, 5, 126206, 5),
 (488742, 5, 126512, 5),
 (476503, 5, 126839, 5),
 (481906, 5, 127338, 5),
 (476071, 5, 127375, 5),
 (476218, 5, 127375, 5),
 (476241, 5, 127375, 5),
 (492756, 5, 127686, 5),
 (486113, 5, 128992, 5),
 (478612, 5, 129127, 5),
 (480987, 5, 129410, 5),
 (475751, 5, 135581, 5),
 (475790, 5, 135581, 5),
 (475829, 5, 135581, 5),
 (479709, 5, 136980, 5),
 (488741, 5, 137017, 5),
 (488753, 5, 137044, 5),
 (476944, 5, 137077, 5),
 (479715, 5, 137103, 5),
 (488741, 5, 138210, 5),
 (478006, 5, 138837, 5),
 (478192, 5, 138837, 5),
 (478007, 5, 138838, 5),
 (478193, 5, 138838, 5),
 (489165, 5, 138909, 5),
 (489166, 5, 138910, 5),
 (475751, 5, 140033, 5),
 (475790, 5, 140033, 5),
 (475829, 5, 140033, 5),
 (476999, 5, 140480, 5),
 (476503, 5, 142214, 5),
 (475812, 5, 143204, 5),
 (476503, 5, 143391, 5),
 (488718, 5, 143739, 5),
 (476503, 5, 144194, 5),
 (476503, 5, 144549, 5),
 (481517, 5, 145679, 5),
 (476503, 5, 146713, 5),
 (492787, 5, 146941, 5),
 (489166, 5, 147983, 5),
 (475784, 5, 148796, 5),
 (475785, 5, 148797, 5),
 (475786, 5, 148798, 5),
 (475784, 5, 148819, 5),
 (475785, 5, 148820, 5),
 (475786, 5, 148821, 5),
 (475784, 5, 148897, 5),
 (475785, 5, 148898, 5),
 (475786, 5, 148899, 5),
 (475750, 5, 149322, 5),
 (475789, 5, 149322, 5),
 (475828, 5, 149322, 5),
 (475751, 5, 149323, 5),
 (475790, 5, 149323, 5),
 (475829, 5, 149323, 5),
 (476071, 5, 149379, 5),
 (476218, 5, 149379, 5),
 (476241, 5, 149379, 5),
 (476503, 5, 149525, 5),
 (476503, 5, 151067, 5),
 (492762, 5, 151388, 5),
 (481517, 5, 152241, 5),
 (479945, 5, 152348, 5),
 (485647, 5, 154618, 5),
 (486113, 5, 154990, 5),
 (484076, 5, 155243, 5),
 (485243, 5, 156097, 5),
 (482300, 5, 156152, 5),
 (475751, 5, 157368, 5),
 (475790, 5, 157368, 5),
 (475829, 5, 157368, 5),
 (492756, 5, 157737, 5),
 (475787, 5, 157938, 5),
 (475788, 5, 157939, 5),
 (475827, 5, 157939, 5),
 (475750, 5, 157940, 5),
 (475789, 5, 157940, 5),
 (475828, 5, 157940, 5),
 (475751, 5, 157941, 5),
 (475790, 5, 157941, 5),
 (475829, 5, 157941, 5),
 (476503, 5, 158441, 5),
 (492756, 5, 159797, 5),
 (475751, 5, 161383, 5),
 (475790, 5, 161383, 5),
 (475829, 5, 161383, 5),
 (492756, 5, 162755, 5),
 (479715, 5, 163437, 5),
 (476503, 5, 165806, 5),
 (476503, 5, 166020, 5),
 (476503, 5, 167920, 5),
 (492756, 5, 168024, 5),
 (476503, 5, 168422, 5),
 (493213, 5, 168435, 5),
 (476503, 5, 168451, 5),
 (482957, 5, 168531, 5),
 (482957, 5, 168605, 5),
 (476503, 5, 169270, 5),
 (476503, 5, 169382, 5),
 (476503, 5, 169389, 5),
 (486021, 5, 170013, 5),
 (486054, 5, 170455, 5),
 (485243, 5, 170747, 5),
 (476503, 5, 171203, 5),
 (476503, 5, 171417, 5),
 (476503, 5, 172074, 5),
 (485361, 5, 175603, 5),
 (482136, 5, 176715, 5),
 (482152, 5, 176715, 5),
 (492756, 5, 177602, 5),
 (492756, 5, 177796, 5),
 (475934, 5, 180351, 5),
 (475935, 5, 180352, 5),
 (477519, 5, 181236, 5),
 (475935, 5, 181659, 5),
 (485243, 5, 182718, 5),
 (488718, 5, 183331, 5),
 (479709, 5, 183631, 5),
 (479709, 5, 183702, 5),
 (481517, 5, 184781, 5),
 (481518, 5, 184782, 5),
 (481519, 5, 184783, 5),
 (475787, 5, 184904, 5),
 (475788, 5, 184905, 5),
 (475827, 5, 184905, 5),
 (475750, 5, 184906, 5),
 (475789, 5, 184906, 5),
 (475828, 5, 184906, 5),
 (475751, 5, 184907, 5),
 (475790, 5, 184907, 5),
 (475829, 5, 184907, 5),
 (475751, 5, 184924, 5),
 (475790, 5, 184924, 5),
 (475829, 5, 184924, 5),
 (492755, 5, 185578, 5),
 (492756, 5, 185579, 5),
 (486544, 5, 185592, 5),
 (492756, 5, 185597, 5),
 (489977, 5, 186102, 5),
 (482047, 5, 186653, 5),
 (492756, 5, 188118, 5),
 (491534, 5, 188363, 5),
 (491535, 5, 188364, 5),
 (479715, 5, 189514, 5),
 (476503, 5, 190092, 5),
 (492804, 5, 196387, 5),
 (479709, 5, 196760, 5),
 (478612, 5, 196926, 5),
 (483605, 5, 197584, 5),
 (489348, 5, 197830, 5),
 (490118, 5, 197830, 5),
 (475935, 5, 201786, 5),
 (475935, 5, 201826, 5),
 (488745, 5, 202010, 5),
 (493213, 5, 204529, 5),
 (479709, 5, 206985, 5),
 (480596, 5, 207122, 5),
 (487462, 5, 207570, 5),
 (475935, 5, 208453, 5),
 (482957, 5, 208506, 5),
 (476944, 5, 208919, 5),
 (485126, 5, 209091, 5),
 (485145, 5, 209815, 5),
 (485243, 5, 210090, 5),
 (482585, 5, 210882, 5),
 (481517, 5, 212479, 5),
 (492756, 5, 212534, 5),
 (478612, 5, 216233, 5),
 (486544, 5, 218082, 5),
 (476381, 5, 218150, 5),
 (476503, 5, 220257, 5),
 (492756, 5, 220829, 5),
 (492756, 5, 220904, 5),
 (482300, 5, 221405, 5),
 (481517, 5, 222456, 5),
 (479204, 5, 224523, 5),
 (479205, 5, 224524, 5),
 (475751, 5, 224741, 5),
 (475790, 5, 224741, 5),
 (475829, 5, 224741, 5),
 (492028, 5, 228621, 5),
 (478563, 5, 228940, 5),
 (489166, 5, 229759, 5),
 (481087, 5, 229886, 5),
 (476071, 5, 232602, 5),
 (476218, 5, 232602, 5),
 (476241, 5, 232602, 5),
 (475429, 5, 234063, 5),
 (475750, 5, 237633, 5),
 (475789, 5, 237633, 5),
 (475828, 5, 237633, 5),
 (475751, 5, 237634, 5),
 (475790, 5, 237634, 5),
 (475829, 5, 237634, 5),
 (475787, 5, 237752, 5),
 (475788, 5, 237753, 5),
 (475827, 5, 237753, 5),
 (475750, 5, 237754, 5),
 (475789, 5, 237754, 5),
 (475828, 5, 237754, 5),
 (475751, 5, 237755, 5),
 (475790, 5, 237755, 5),
 (475829, 5, 237755, 5),
 (475565, 5, 239039, 5),
 (475934, 5, 239623, 5),
 (475935, 5, 239624, 5),
 (492465, 5, 241536, 5),
 (492465, 5, 241548, 5),
 (482302, 5, 241877, 5),
 (475564, 5, 247634, 5),
 (481519, 5, 247679, 5),
 (476110, 5, 251914, 5),
 (483131, 5, 254052, 5),
 (488741, 5, 254582, 5),
 (486113, 5, 259883, 5),
 (481519, 5, 262113, 5),
 (488607, 5, 264122, 5),
 (488608, 5, 264123, 5),
 (486544, 5, 265447, 5),
 (482302, 5, 265931, 5),
 (480017, 5, 266707, 5),
 (493213, 5, 270734, 5),
 (489994, 5, 270943, 5),
 (489770, 5, 273832, 5),
 (482302, 5, 274482, 5),
 (481519, 5, 275544, 5),
 (478953, 5, 276859, 5),
 (478907, 5, 276860, 5),
 (478954, 5, 276860, 5),
 (482342, 5, 279023, 5),
 (482342, 5, 279174, 5),
 (475885, 5, 280507, 5),
 (489166, 5, 281314, 5),
 (492465, 5, 281686, 5),
 (481519, 5, 283947, 5),
 (476690, 5, 283954, 5),
 (476751, 5, 284713, 5),
 (485126, 5, 284924, 5),
 (483429, 5, 284975, 5),
 (489771, 5, 288707, 5),
 (489949, 5, 288851, 5),
 (487648, 5, 303159, 5),
 (487649, 5, 303160, 5),
 (487650, 5, 303161, 5),
 (482957, 5, 303238, 5),
 (483057, 5, 304210, 5),
 (483121, 5, 304210, 5),
 (484804, 5, 304210, 5),
 (485291, 5, 308787, 5),
 (479360, 5, 309690, 5),
 (485342, 5, 312880, 5),
 (487080, 5, 312880, 5),
 (491111, 5, 312880, 5),
 (491812, 5, 312880, 5),
 (479689, 5, 312881, 5),
 (486763, 5, 312881, 5),
 (479690, 5, 312882, 5),
 (482957, 5, 313292, 5),
 (483057, 5, 313944, 5),
 (483121, 5, 313944, 5),
 (484804, 5, 313944, 5),
 (481593, 5, 314903, 5),
 (482143, 5, 315771, 5),
 (489964, 5, 315771, 5),
 (490813, 5, 315771, 5),
 (476302, 5, 315832, 5),
 (483057, 5, 316393, 5),
 (483121, 5, 316393, 5),
 (484804, 5, 316393, 5),
 (483014, 5, 319828, 5),
 (483015, 5, 319829, 5),
 (489197, 5, 319971, 5),
 (476719, 5, 323924, 5),
 (476720, 5, 323925, 5),
 (476721, 5, 323926, 5),
 (476722, 5, 323927, 5),
 (476723, 5, 323928, 5),
 (476724, 5, 323929, 5),
 (476725, 5, 323930, 5),
 (476153, 5, 326988, 5),
 (481593, 5, 328028, 5),
 (488825, 5, 328859, 5),
 (488826, 5, 328860, 5),
 (488827, 5, 328861, 5),
 (488828, 5, 328862, 5),
 (488829, 5, 328863, 5),
 (488830, 5, 328864, 5),
 (488831, 5, 328865, 5),
 (488832, 5, 328866, 5),
 (488833, 5, 328867, 5),
 (488834, 5, 328868, 5),
 (488142, 5, 330060, 5),
 (488143, 5, 330061, 5),
 (488144, 5, 330062, 5),
 (488145, 5, 330063, 5),
 (488146, 5, 330064, 5),
 (488147, 5, 330065, 5),
 (488148, 5, 330066, 5),
 (488149, 5, 330067, 5),
 (488150, 5, 330068, 5),
 (488151, 5, 330069, 5),
 (488152, 5, 330070, 5),
 (488153, 5, 330071, 5),
 (488154, 5, 330072, 5),
 (488155, 5, 330073, 5),
 (488156, 5, 330074, 5),
 (487510, 5, 330100, 5),
 (489515, 5, 330100, 5),
 (487511, 5, 330101, 5),
 (489516, 5, 330101, 5),
 (475760, 5, 332763, 5),
 (483057, 5, 335975, 5),
 (483121, 5, 335975, 5),
 (484804, 5, 335975, 5),
 (484043, 5, 344927, 5),
 (486363, 5, 344927, 5),
 (486605, 5, 344927, 5),
 (483057, 5, 348360, 5),
 (483121, 5, 348360, 5),
 (484804, 5, 348360, 5),
 (483057, 5, 349203, 5),
 (483121, 5, 349203, 5),
 (484804, 5, 349203, 5),
 (490836, 5, 355339, 5),
 (484421, 5, 355350, 5),
 (481518, 5, 355357, 5),
 (482575, 5, 357240, 5),
 (482582, 5, 357247, 5),
 (482583, 5, 357248, 5),
 (482584, 5, 357249, 5),
 (482585, 5, 357250, 5),
 (482586, 5, 357251, 5),
 (482587, 5, 357252, 5),
 (482588, 5, 357253, 5),
 (482593, 5, 357259, 5),
 (482594, 5, 357260, 5),
 (482595, 5, 357261, 5),
 (482596, 5, 357262, 5),
 (482597, 5, 357263, 5),
 (482598, 5, 357264, 5),
 (482599, 5, 357265, 5),
 (482600, 5, 357266, 5),
 (482601, 5, 357267, 5),
 (482602, 5, 357268, 5),
 (482603, 5, 357269, 5),
 (482604, 5, 357270, 5),
 (482605, 5, 357271, 5),
 (482606, 5, 357272, 5),
 (482607, 5, 357273, 5),
 (482608, 5, 357274, 5),
 (482609, 5, 357275, 5),
 (482610, 5, 357276, 5),
 (482611, 5, 357277, 5),
 (482612, 5, 357278, 5),
 (475787, 5, 357613, 5),
 (475788, 5, 357614, 5),
 (475827, 5, 357614, 5),
 (475750, 5, 357615, 5),
 (475789, 5, 357615, 5),
 (475828, 5, 357615, 5),
 (475751, 5, 357616, 5),
 (475790, 5, 357616, 5),
 (475829, 5, 357616, 5),
 (475791, 5, 357617, 5),
 (482366, 5, 357697, 5),
 (482366, 5, 357777, 5),
 (482366, 5, 357807, 5),
 (476759, 5, 357998, 5),
 (476844, 5, 358366, 5),
 (476845, 5, 358367, 5),
 (476846, 5, 358368, 5),
 (476862, 5, 358387, 5),
 (476863, 5, 358388, 5),
 (475751, 5, 358480, 5),
 (475790, 5, 358480, 5),
 (475829, 5, 358480, 5),
 (482366, 5, 359203, 5),
 (482366, 5, 359356, 5),
 (482366, 5, 359647, 5),
 (482366, 5, 360425, 5),
 (482366, 5, 361520, 5),
 (482957, 5, 361893, 5),
 (482957, 5, 361906, 5),
 (482366, 5, 363292, 5),
 (482366, 5, 363632, 5),
 (482366, 5, 364956, 5),
 (482366, 5, 364980, 5),
 (484100, 5, 365858, 5),
 (484112, 5, 365871, 5),
 (484113, 5, 365872, 5),
 (484114, 5, 365873, 5),
 (484115, 5, 365874, 5),
 (492028, 5, 369017, 5),
 (481519, 5, 370164, 5),
 (481087, 5, 370408, 5),
 (476325, 5, 370469, 5),
 (476326, 5, 370470, 5),
 (476327, 5, 370471, 5),
 (476328, 5, 370472, 5),
 (476329, 5, 370473, 5),
 (476330, 5, 370474, 5),
 (476331, 5, 370475, 5),
 (476332, 5, 370476, 5),
 (476333, 5, 370477, 5),
 (478563, 5, 370846, 5),
 (481734, 5, 371543, 5),
 (481774, 5, 371589, 5),
 (478563, 5, 375146, 5),
 (489197, 5, 377275, 5),
 (487583, 5, 377650, 5),
 (478563, 5, 379042, 5),
 (485126, 5, 381827, 5),
 (478563, 5, 383063, 5),
 (490836, 5, 383435, 5),
 (482587, 5, 383875, 5),
 (482587, 5, 383899, 5),
 (482366, 5, 384679, 5),
 (479354, 5, 389843, 5),
 (476152, 5, 390052, 5),
 (489165, 5, 391063, 5),
 (489166, 5, 391064, 5),
 (476503, 5, 391369, 5),
 (482587, 5, 392110, 5),
 (491095, 5, 396395, 5),
 (482587, 5, 396447, 5),
 (488027, 5, 396935, 5),
 (492465, 5, 397222, 5),
 (485547, 5, 402500, 5),
 (481906, 5, 402501, 5),
 (490955, 5, 402841, 5),
 (486113, 5, 403915, 5),
 (486113, 5, 404604, 5),
 (476850, 5, 405152, 5),
 (489166, 5, 409778, 5),
 (476590, 5, 413154, 5),
 (489180, 5, 413233, 5),
 (485647, 5, 415045, 5),
 (476503, 5, 416702, 5),
 (485361, 5, 419222, 5),
 (485361, 5, 419325, 5),
 (492465, 5, 421473, 5),
 (489564, 5, 422855, 5),
 (488742, 5, 423080, 5),
 (488742, 5, 423457, 5),
 (487462, 5, 425844, 5),
 (492756, 5, 426454, 5),
 (483884, 5, 428626, 5),
 (492755, 5, 428658, 5),
 (479354, 5, 429481, 5),
 (482367, 5, 429990, 5),
 (482957, 5, 430471, 5),
 (482957, 5, 430658, 5),
 (482957, 5, 430947, 5),
 (489180, 5, 431997, 5),
 (480604, 5, 433769, 5),
 (480604, 5, 433802, 5),
 (492464, 5, 434669, 5),
 (482366, 5, 435046, 5),
 (482366, 5, 435276, 5),
 (479354, 5, 435330, 5),
 (482957, 5, 435331, 5),
 (482366, 5, 435675, 5),
 (492756, 5, 439700, 5),
 (493213, 5, 439739, 5),
 (476153, 5, 440053, 5),
 (476503, 5, 441421, 5),
 (481087, 5, 442897, 5),
 (483145, 5, 444662, 5),
 (483289, 5, 444662, 5),
 (483145, 5, 444759, 5),
 (483289, 5, 444759, 5),
 (483145, 5, 444886, 5),
 (483289, 5, 444886, 5),
 (483145, 5, 445008, 5),
 (483289, 5, 445008, 5),
 (480764, 5, 445207, 5),
 (489349, 5, 446714, 5),
 (485720, 5, 447223, 5),
 (480764, 5, 448261, 5),

In [ ]:
references["old_text"].value_counts()

old_text
και θησομαι εις τον αιωνα του αιωνος το σπερμα αυτου και τον θρονον αυτου ως τας ημερας του ουρανου                                                                                                                           22
εσκορπισεν εδωκεν τοις πενησιν η δικαιοσυνη αυτου μενει εις τον αιωνα του αιωνος το κερας αυτου υψωθησεται εν δοξη                                                                                                            22
αινεσιν κυριου λαλησει το στομα μου και ευλογειτω πασα σαρξ το ονομα το αγιον αυτου εις τον αιωνα και εις τον αιωνα του αιωνος αλληλουια αγγαιου και ζαχαριου αινει η ψυχη μου τον κυριον                                     21
εξομολογησις και μεγαλοπρεπεια το εργον αυτου και η δικαιοσυνη αυτου μενει εις τον αιωνα του αιωνος μνειαν εποιησατο των θαυμασιων αυτου ελεημων και οικτιρμων ο κυριος                                                       21
αινεσις τω δαυιδ υψωσω σε ο θεος μου ο βασιλευς μου και ευλογησω το ονομα σου εις τον αιωνα και εις τον αιωνα του αιωνος καθ εκαστην ημεραν ευλογησω σε και αινεσω το ονομα σου εις τον αιωνα και εις τον αιωνα του αιωνος    21
                                                                                                                                                                                                                              ..
εξετηξεν με ο ζηλος του οικου σου οτι επελαθοντο των λογων σου οι εχθροι μου                                                                                                                                                   1
οτι ο ζηλος του οικου σου κατεφαγεν με και οι ονειδισμοι των ονειδιζοντων σε επεπεσαν επ εμε                                                                                                                                   1
και εκηρυχθη και ερρεθη εν τη νινευη παρα του βασιλεως και παρα των μεγιστανων αυτου λεγων οι ανθρωποι και τα κτηνη και οι βοες και τα προβατα μη γευσασθωσαν μηδεν μηδε νεμεσθωσαν μηδε υδωρ πιετωσαν                         1
εφοβηθη δε ιακωβ σφοδρα και ηπορειτο και διειλεν τον λαον τον μετ αυτου και τους βοας και τα προβατα εις δυο παρεμβολας                                                                                                        1
και εσονται υμιν παντα τα ρηματα ταυτα ως οι λογοι του βιβλιου του εσφραγισμενου τουτου ο εαν δωσιν αυτο ανθρωπω επισταμενω γραμματα λεγοντες αναγνωθι ταυτα και ερει ου δυναμαι αναγνωναι εσφραγισται γαρ                     1
Name: count, Length: 2337, dtype: int64

In [ ]:
bible["text"].value_counts()[20:]

text
προς              3546
δε                3505
κυριος            3382
οτι               3217
ὁ                 2882
                  ...
αποβιαζου            1
προβαλλομενοις       1
αποκρινεσθαι         1
απογραψαι            1
ἀφελεῖ               1
Name: count, Length: 52720, dtype: int64